<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_drive_car">

  <!-- 引入差速驱动插件 -->
  <xacro:include filename="$(find botlab_diff_description)/urdf/gazebo_control_plugin.xacro"/>

  <!-- 参数定义 -->
  <xacro:property name="chassis_length" value="0.26"/>     <!-- 底盘长度 26cm -->
  <xacro:property name="chassis_width"  value="0.22"/>     <!-- 底盘宽度 22cm -->
  <xacro:property name="chassis_height" value="0.08"/>    <!-- 底盘高度 8cm -->
  <xacro:property name="wheel_radius"   value="0.0325"/>  <!-- 轮子半径 3.25cm（直径6.5cm） -->
  <xacro:property name="wheel_width"    value="0.02"/>    <!-- 轮胎厚度 2cm -->
  <xacro:property name="wheelbase"      value="0.18"/>    <!-- 前后轮距 -->
  <xacro:property name="track"          value="0.20"/>    <!-- 左右轮距 -->

  <!-- 底盘 -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + chassis_height/2}" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0.1 0.4 0.8 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${wheel_radius + chassis_height/2}" rpy="0 0 0"/>
    </collision>

    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.08"/>
    </inertial>
  </link>

  <!-- Gazebo 物理标签 -->
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- 定义轮子模板 -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="wheel_${prefix}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="black">
          <color rgba="0.02 0.02 0.02 1"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>

      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
      </inertial>


    </link>

    <joint name="joint_${prefix}" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_${prefix}"/>
        <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.1" friction="0.1"/>
      </joint>
  </xacro:macro>

  <!-- Gazebo 物理属性 -->
  <gazebo reference="wheel_${prefix}">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
    <minDepth>0.001</minDepth>
    <maxVel>1.0</maxVel>
  </gazebo>

  <!-- 四个轮子 -->
  <xacro:wheel prefix="fl" x="${ wheelbase/2}"  y="${ track/2}"/>
  <xacro:wheel prefix="fr" x="${ wheelbase/2}"  y="-${ track/2}"/>
  <xacro:wheel prefix="rl" x="-${wheelbase/2}"  y="${ track/2}"/>
  <xacro:wheel prefix="rr" x="-${wheelbase/2}"  y="-${ track/2}"/>

  <!-- 使用差速驱动插件 -->
  <xacro:gazebo_control_plugin/>

</robot>
