<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:macro name="gazebo_control_plugin">
        <!-- 差速驱动插件 - 使用后轮作为驱动轮 -->
        <gazebo>
            <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
                <ros>
                    <namespace>/</namespace>
                    <remapping>cmd_vel:=cmd_vel</remapping>
                    <remapping>odom:=odom</remapping>
                </ros>
                
                <update_rate>50</update_rate>
                
                <!-- 后轮作为驱动轮 -->
                <left_joint>joint_rl</left_joint>
                <right_joint>joint_rr</right_joint>
                
                <!-- 运动学参数 -->
                <wheel_separation>${track}</wheel_separation>
                <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
                
                <!-- 限制参数 -->
                <max_wheel_torque>50</max_wheel_torque>
                <max_wheel_acceleration>5.0</max_wheel_acceleration>
                
                <!-- 控制参数 -->
                <command_topic>cmd_vel</command_topic>
                <odometry_topic>odom</odometry_topic>
                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_link</robot_base_frame>
                
                <!-- 输出设置 -->
                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>false</publish_wheel_tf>
                
                <!-- 坐标系设置 -->
                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_link</robot_base_frame>
            </plugin>
        </gazebo>
        
        <!-- 前轮跟随插件 - 让前轮被动跟随 -->
        <gazebo reference="joint_fl">
            <provideFeedback>true</provideFeedback>
        </gazebo>
        <gazebo reference="joint_fr">
            <provideFeedback>true</provideFeedback>
        </gazebo>
        
        <!-- 关节状态发布器 - 发布所有轮子的状态 -->
        <gazebo>
            <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
                <ros>
                    <namespace>/</namespace>
                    <remapping>~/out:=joint_states</remapping>
                </ros>
                <update_rate>50</update_rate>
                <joint_name>joint_fl</joint_name>
                <joint_name>joint_fr</joint_name>
                <joint_name>joint_rl</joint_name>
                <joint_name>joint_rr</joint_name>
            </plugin>
        </gazebo>
        
    </xacro:macro>
    
</robot>