<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="botlab_zero">

  <!-- 引入模块 -->
  <xacro:include filename="$(find botlab_diff_description)/urdf/botlab_zero/base.urdf.xacro"/>
  <xacro:include filename="$(find botlab_diff_description)/urdf/botlab_zero/wheel.urdf.xacro"/>
  <xacro:include filename="$(find botlab_diff_description)/urdf/botlab_zero/control.urdf.xacro"/>

  <!-- 参数定义（保持与原机器人一致） -->
  <xacro:property name="chassis_length" value="0.26"/>     <!-- 底盘长度 26cm -->
  <xacro:property name="chassis_width"  value="0.22"/>     <!-- 底盘宽度 22cm -->
  <xacro:property name="chassis_height" value="0.08"/>     <!-- 底盘高度 8cm -->
  <xacro:property name="wheel_radius"   value="0.0325"/>   <!-- 轮子半径 3.25cm -->
  <xacro:property name="wheel_width"    value="0.03"/>     <!-- 轮胎厚度 3cm -->
  <xacro:property name="wheelbase"      value="0.18"/>     <!-- 前后轮距 -->
  <xacro:property name="track"          value="0.20"/>     <!-- 左右轮距 -->

  <!-- 底盘模块 -->
  <xacro:base
    chassis_length="${chassis_length}"
    chassis_width="${chassis_width}"
    chassis_height="${chassis_height}"
    wheel_radius="${wheel_radius}"/>

  <!-- 四个轮子：位置完全复刻原机器人 -->
  <xacro:wheel prefix="fl"
               x="${ wheelbase/2}"
               y="${ track/2}"
               wheel_radius="${wheel_radius}"
               wheel_width="${wheel_width}"/>

  <xacro:wheel prefix="fr"
               x="${ wheelbase/2}"
               y="-${ track/2}"
               wheel_radius="${wheel_radius}"
               wheel_width="${wheel_width}"/>

  <xacro:wheel prefix="rl"
               x="-${ wheelbase/2}"
               y="${ track/2}"
               wheel_radius="${wheel_radius}"
               wheel_width="${wheel_width}"/>

  <xacro:wheel prefix="rr"
               x="-${ wheelbase/2}"
               y="-${ track/2}"
               wheel_radius="${wheel_radius}"
               wheel_width="${wheel_width}"/>

  <!-- ros2_control system -->
  <ros2_control name="botlab_zero_hw" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="joint_fl">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_fr">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_rl">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="joint_rr">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- Gazebo 配置 -->
  <gazebo reference="base_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- ROS2 Control 插件 -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find botlab_diff_description)/config/botlab_zero_controllers.yaml</parameters>
      <ros>
        <remapping>/diff_drive_controller/cmd_vel_unstamped:=/cmd_vel</remapping>
        <remapping>/diff_drive_controller/odom:=/odom</remapping>
      </ros>
    </plugin>
  </gazebo>
</robot>
