controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_fl
      - joint_fr
      - joint_rl
      - joint_rr

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_fl", "joint_rl"]
    right_wheel_names: ["joint_fr", "joint_rr"]
    wheel_separation: 0.20
    wheel_radius: 0.0325
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    cmd_vel_timeout: 0.5
    use_stamped_vel: false